name: test and analyze master branch

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    buildAndTest:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Forge build
              run: forge build

            - name: Run unit tests (forge)
              run: forge test

            - name: Run coverage
              run: forge coverage --report lcov

            - name: Report coverage
              uses: codecov/codecov-action@v3
              with:
                  files: lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Run int tests
              run: yarn hh:test

            - name: Run Slither
              uses: crytic/slither-action@v0.3.1
              id: slither
              with:
                  node-version: 20
                  sarif: results.sarif
                  fail-on: none

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: ${{ steps.slither.outputs.sarif }}
