name: build and test

on: [pull_request]

jobs:
    buildAndTest:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Forge build
              run: forge build

            - name: Run unit tests (forge)
              run: forge test

            - name: Run coverage
              run: forge coverage --report lcov

            - name: Report coverage
              uses: codecov/codecov-action@v3
              with:
                  files: lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Run int tests
              run: yarn hh:test
