name: build and test

on: [pull_request]

jobs:
    buildAndTest:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: yarn install

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Run unit tests (forge)
              run: forge test

            - name: Compile hardhat
              run: yarn compile

            - name: Run int tests 
              run: yarn hh:test

            - name: Run int coverage 
              run: yarn coverage
