name: slither analyzer

on: [pull_request]

jobs:
    slither:
        name: Run slither
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: crytic/slither-action@dev
              with:
                  node-version: 16
                  target: "."
